services:
  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: controle-patrimonial
    container_name: controle-patrimonial-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - controle-patrimonial

  db:
    image: mysql:8.0
    container_name: controle-patrimonial-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3308:3306"
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - controle-patrimonial

  nginx:
    image: nginx:alpine
    container_name: controle-patrimonial-nginx
    restart: unless-stopped
    ports:
      - "8002:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - controle-patrimonial

networks:
  controle-patrimonial:
    driver: bridge

volumes:
  mysql_data:
